version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install GIT
          command: 'apt-get update && sudo apt-get install -y git'
      - run:
          name: Installing Minisat
          command: 'git clone https://github.com/master-keying/minisat.git && cd minisat && mkdir build && cd build && cmake .. && make && make install'
      - run:
          name: Installing Minisat
          command: 'git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install'
      - run:
          name: Build Suduku Solver
          command: 'cd example && cmake .. && make'
      - run:
          name: Run examples
          command: 'cd example && ./sudoku-solver 1 && ./sudoku-solver 2'
      - run:
          name: Run tests
          command: 'cd example && ./sudoku-solver-test'

